import { useEffect, useState } from 'react';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { Mail, Lock } from 'lucide-react-native';
import { Platform, Pressable, Text, View } from 'react-native';
import { Image } from 'expo-image';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import { useTranslation } from 'react-i18next';
import { PrimaryButton, Screen, TextField, Title } from '@/components/brand';
import { Colors } from '@/constants/theme';
import { exchangeOAuthCallback } from '@/features/auth/oauth-callback';
import { preferences } from '@/lib/preferences';
import { requireSupabase } from '@/lib/supabase';
import { hasVerifiedPhone } from '@/features/auth/phone-verification';

export default function AuthScreen(){const {t}=useTranslation();const params=useLocalSearchParams<{passwordReset?:string}>();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'login'|'signup'|'forgot'|'resetSent'|'confirmation'>('login');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [messageKind,setMessageKind]=useState<'error'|'success'>('error');
  useEffect(()=>{if(params.passwordReset==='success'){setMode('login');setPassword('');setMessageKind('success');setMessage(t('auth.passwordUpdated'))}},[params.passwordReset,t]);
  const continueAfterAuth=async()=>{const {data:{user}}=await requireSupabase().auth.getUser();if(!user){router.replace('/auth');return}if(!hasVerifiedPhone(user)){router.replace('/auth/verify-phone' as Href);return}const {data}=await requireSupabase().from('birth_profiles').select('id').eq('user_id',user.id).eq('relationship','self').maybeSingle();if(data)await preferences.setOnboardingComplete(true);router.replace(data?'/home':'/profile-setup')};
  const submit=async()=>{setBusy(true);setMessage('');try{const db=requireSupabase();if(mode==='forgot'){if(!email.trim()){setMessageKind('error');setMessage(t('auth.enterEmailFirst'));return}const redirectTo=`${Linking.createURL('auth/callback')}?flow=recovery`;const {error}=await db.auth.resetPasswordForEmail(email.trim(),{redirectTo});if(error)throw error;setMode('resetSent');return}if(!email.trim()||!password){setMessageKind('error');setMessage(t('auth.enterEmailPassword'));return}if(mode==='signup'){const {data,error}=await db.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:Linking.createURL('auth/callback')}});if(error)throw error;if(data.user?.identities?.length===0){setMode('login');setMessageKind('error');setMessage(t('auth.accountExists'));return}if(!data.session){setMode('confirmation');return}await continueAfterAuth();return}const {error}=await db.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;await continueAfterAuth()}catch(e){if(mode==='signup'&&e instanceof Error&&e.message.toLowerCase().includes('user already registered')){setMode('login');setMessageKind('error');setMessage(t('auth.accountExists'))}else{setMessageKind('error');setMessage(e instanceof Error?e.message:t('auth.unableToContinue'))}}finally{setBusy(false)}};
  const oauth=async(provider:'google'|'apple')=>{setBusy(true);setMessage('');try{const db=requireSupabase();const redirectTo=Linking.createURL('auth/callback');const {data,error}=await db.auth.signInWithOAuth({provider,options:{redirectTo,skipBrowserRedirect:true}});if(error)throw error;if(!data.url)throw new Error(provider==='google'?t('auth.googleNoUrl'):t('auth.appleNoUrl'));if(Platform.OS==='web'){window.location.assign(data.url);return;}const result=await WebBrowser.openAuthSessionAsync(data.url,redirectTo);if(result.type==='success'){try{await exchangeOAuthCallback(db.auth,result.url)}catch(exchangeError){
  // The /auth/callback deep-link route can win a race and consume the one-time PKCE code
  // before this handler gets to it. If a session already exists despite the failure, the
  // other handler already finished the sign-in, so continue instead of surfacing an error.
  const {data:{session}}=await db.auth.getSession();if(!session)throw exchangeError;
}await continueAfterAuth();}}catch(e){setMessageKind('error');setMessage(e instanceof Error?e.message:t('auth.socialUnavailable'))}finally{setBusy(false)}};
  return <Screen scroll style={{paddingTop:26}}><View style={{flex:1,justifyContent:'flex-start'}}><Image source={require('../../assets/images/star-talks-mark.png')} contentFit="contain" accessibilityLabel="Star Talks" style={{width:86,height:43,alignSelf:'center',marginBottom:3}}/><Title subtitle={mode==='forgot'?t('auth.forgotSubtitle'):mode==='resetSent'?t('auth.resetSentSubtitle'):t('auth.welcomeSubtitle')}>{mode==='signup'?t('auth.signupTitle'):mode==='forgot'?t('auth.forgotTitle'):mode==='resetSent'?t('auth.resetSentTitle'):mode==='confirmation'?t('auth.confirmationTitle'):t('auth.welcomeTitle')}</Title>{mode==='confirmation'?<Text style={{fontFamily:'Poppins_400Regular',fontSize:13,lineHeight:21,color:Colors.muted,textAlign:'center',marginTop:10,marginBottom:20}}>{t('auth.confirmationBody',{email:email.trim()})}</Text>:mode==='resetSent'?<Text style={{fontFamily:'Poppins_400Regular',fontSize:13,lineHeight:21,color:Colors.muted,textAlign:'center',marginTop:10,marginBottom:20}}>{t('auth.resetSentBody',{email:email.trim()})}</Text>:<><TextField label={t('auth.emailLabel')} icon={<Mail size={16} color={Colors.muted}/>} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder={t('auth.emailPlaceholder')}/>{mode==='forgot'?null:<TextField label={t('auth.passwordLabel')} icon={<Lock size={16} color={Colors.muted}/>} secure value={password} onChangeText={setPassword} placeholder={t('auth.passwordPlaceholder')}/>}</>}
    {message?<Text accessibilityRole="alert" style={{color:messageKind==='success'?Colors.success:Colors.danger,fontFamily:'Poppins_400Regular',fontSize:11,marginBottom:8}}>{message}</Text>:null}
    {mode==='confirmation'||mode==='resetSent'?<PrimaryButton title={t('auth.backToLogin')} onPress={()=>{setMode('login');setMessage('')}}/>:<PrimaryButton title={mode==='signup'?t('auth.signUpBtn'):mode==='forgot'?t('auth.sendResetLink'):t('auth.logInBtn')} loading={busy} onPress={submit}/>}
    {mode==='login'?<Pressable onPress={()=>{setMode('forgot');setMessage('')}} style={{padding:12,alignItems:'center'}}><Text style={{color:Colors.indigo,fontFamily:'Poppins_500Medium',fontSize:11}}>{t('auth.forgotPassword')}</Text></Pressable>:mode==='forgot'?<Pressable onPress={()=>{setMode('login');setMessage('')}} style={{padding:12,alignItems:'center'}}><Text style={{color:Colors.indigo,fontFamily:'Poppins_500Medium',fontSize:11}}>{t('auth.backToLogin')}</Text></Pressable>:null}
    {mode==='login'||mode==='signup'?<><View style={{flexDirection:'row',alignItems:'center',gap:10,marginVertical:14}}><View style={{height:1,flex:1,backgroundColor:'#E5E3DF'}}/><Text style={{color:Colors.muted,fontFamily:'Poppins_400Regular',fontSize:11}}>{t('auth.or')}</Text><View style={{height:1,flex:1,backgroundColor:'#E5E3DF'}}/></View>
    <Pressable disabled={busy} onPress={()=>oauth('google')} style={{height:44,borderRadius:9,borderWidth:1,borderColor:'#E5E3DF',backgroundColor:'white',alignItems:'center',justifyContent:'center',marginBottom:9}}><Text style={{fontFamily:'Poppins_500Medium',fontSize:12,color:Colors.text}}>G   {t('auth.continueWithGoogle')}</Text></Pressable>
    <Pressable disabled={busy} onPress={()=>oauth('apple')} style={{height:44,borderRadius:9,borderWidth:1,borderColor:'#E5E3DF',backgroundColor:'white',alignItems:'center',justifyContent:'center'}}><Text style={{fontFamily:'Poppins_500Medium',fontSize:12,color:Colors.text}}>   {t('auth.continueWithApple')}</Text></Pressable>
    <Pressable onPress={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}} style={{padding:16,alignItems:'center'}}><Text style={{fontFamily:'Poppins_400Regular',fontSize:11,color:Colors.muted}}>{mode==='signup'?t('auth.alreadyHaveAccount'):t('auth.newToStarTalks')}<Text style={{color:Colors.indigo,fontFamily:'Poppins_600SemiBold'}}>{mode==='signup'?t('auth.logIn'):t('auth.signUp')}</Text></Text></Pressable></>:null}
  </View></Screen>
}
