import { useState } from 'react';
import { router } from 'expo-router';
import { Mail, Lock } from 'lucide-react-native';
import { Platform, Pressable, Text, View } from 'react-native';
import { Image } from 'expo-image';
import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import { PrimaryButton, Screen, TextField, Title } from '@/components/brand';
import { Colors } from '@/constants/theme';
import { exchangeOAuthCallback } from '@/features/auth/oauth-callback';
import { requireSupabase } from '@/lib/supabase';

export default function AuthScreen(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [otp,setOtp]=useState('');const [mode,setMode]=useState<'login'|'signup'|'verify'|'confirmation'>('login');const [verifyType,setVerifyType]=useState<'signup'|'email'>('signup');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const continueAfterAuth=async()=>{const {data:{user}}=await requireSupabase().auth.getUser();if(!user){router.replace('/profile');return}const {data}=await requireSupabase().from('birth_profiles').select('id').eq('user_id',user.id).eq('relationship','self').maybeSingle();router.replace(data?'/home':'/profile')};
  const submit=async()=>{setBusy(true);setMessage('');try{const db=requireSupabase();if(mode==='verify'){const {error}=await db.auth.verifyOtp({email:email.trim(),token:otp,type:verifyType});if(error)throw error;await continueAfterAuth();return}if(!email.trim()||!password){setMessage('Enter your email and password to continue.');return}if(mode==='signup'){const {data,error}=await db.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:Linking.createURL('auth/callback')}});if(error)throw error;if(!data.session){setMode('confirmation');return}router.replace('/profile');return}const {error}=await db.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;await continueAfterAuth()}catch(e){setMessage(e instanceof Error?e.message:'Unable to sign in. Please try again.')}finally{setBusy(false)}};
  const oauth=async(provider:'google'|'apple')=>{setBusy(true);setMessage('');try{const db=requireSupabase();const redirectTo=Linking.createURL('auth/callback');const {data,error}=await db.auth.signInWithOAuth({provider,options:{redirectTo,skipBrowserRedirect:true}});if(error)throw error;if(!data.url)throw new Error(`${provider==='google'?'Google':'Apple'} sign-in did not return an authorization URL.`);if(Platform.OS==='web'){window.location.assign(data.url);return;}const result=await WebBrowser.openAuthSessionAsync(data.url,redirectTo);if(result.type==='success'){await exchangeOAuthCallback(db.auth,result.url);await continueAfterAuth();}}catch(e){setMessage(e instanceof Error?e.message:'Social sign-in is unavailable. Check that this provider is enabled in Star Talks Supabase Auth.')}finally{setBusy(false)}};
  return <Screen scroll style={{paddingTop:26}}><View style={{flex:1,justifyContent:'flex-start'}}><Image source={require('../../assets/images/star-talks-mark.png')} contentFit="contain" accessibilityLabel="Star Talks" style={{width:86,height:43,alignSelf:'center',marginBottom:3}}/><Title subtitle="Sign in to continue your journey">{mode==='signup'?'Create Your Account':mode==='verify'?'Verify your email':mode==='confirmation'?'Check your email':'Welcome Back'}</Title>{mode==='confirmation'?<Text style={{fontFamily:'Poppins_400Regular',fontSize:13,lineHeight:21,color:Colors.muted,textAlign:'center',marginTop:10,marginBottom:20}}>We sent a confirmation link to {email.trim()}. Open it on this device to finish creating your account. No code is needed.</Text>:mode==='verify'?<TextField label="Verification code" value={otp} onChangeText={setOtp} keyboardType="number-pad" placeholder="Enter the code from your email"/>:<><TextField label="Email" icon={<Mail size={16} color={Colors.muted}/>} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="Email address"/><TextField label="Password" icon={<Lock size={16} color={Colors.muted}/>} secure value={password} onChangeText={setPassword} placeholder="Password"/></>}
    {message?<Text accessibilityRole="alert" style={{color:message.includes('sent')?Colors.success:Colors.danger,fontFamily:'Poppins_400Regular',fontSize:11,marginBottom:8}}>{message}</Text>:null}
    {mode==='confirmation'?<PrimaryButton title="Back to Log In" onPress={()=>{setMode('login');setMessage('')}}/>:<PrimaryButton title={mode==='signup'?'Sign Up':mode==='verify'?'Verify Email':'Log In'} loading={busy} onPress={submit}/>}
    {mode==='login'?<Pressable onPress={async()=>{if(!email.trim()){setMessage('Enter your email first to receive a sign-in code.');return}try{const {error}=await requireSupabase().auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:Linking.createURL('auth/callback')}});if(error)throw error;setVerifyType('email');setMode('verify');setMessage('We sent a sign-in email. Tap its link or enter the code here.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to send code.')}}} style={{padding:12,alignItems:'center'}}><Text style={{color:Colors.indigo,fontFamily:'Poppins_500Medium',fontSize:11}}>Forgot password? Get a sign-in code</Text></Pressable>:null}
    {mode==='confirmation'?null:<><View style={{flexDirection:'row',alignItems:'center',gap:10,marginVertical:14}}><View style={{height:1,flex:1,backgroundColor:'#E5E3DF'}}/><Text style={{color:Colors.muted,fontFamily:'Poppins_400Regular',fontSize:11}}>OR</Text><View style={{height:1,flex:1,backgroundColor:'#E5E3DF'}}/></View>
    <Pressable disabled={busy} onPress={()=>oauth('google')} style={{height:44,borderRadius:9,borderWidth:1,borderColor:'#E5E3DF',backgroundColor:'white',alignItems:'center',justifyContent:'center',marginBottom:9}}><Text style={{fontFamily:'Poppins_500Medium',fontSize:12,color:Colors.text}}>G   Continue with Google</Text></Pressable>
    <Pressable disabled={busy} onPress={()=>oauth('apple')} style={{height:44,borderRadius:9,borderWidth:1,borderColor:'#E5E3DF',backgroundColor:'white',alignItems:'center',justifyContent:'center'}}><Text style={{fontFamily:'Poppins_500Medium',fontSize:12,color:Colors.text}}>   Continue with Apple</Text></Pressable>
    <Pressable onPress={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}} style={{padding:16,alignItems:'center'}}><Text style={{fontFamily:'Poppins_400Regular',fontSize:11,color:Colors.muted}}>{mode==='signup'?'Already have an account? ':'New to Star Talks? '}<Text style={{color:Colors.indigo,fontFamily:'Poppins_600SemiBold'}}>{mode==='signup'?'Log in':'Sign up'}</Text></Text></Pressable></>}
  </View></Screen>
}
