import { Bell, BookOpen, CalendarDays, ChevronRight, CircleUserRound, Compass, Home, MoonStar, Sparkles, Stars, Wallet } from 'lucide-react-native';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { Screen } from '@/components/brand';
import { Colors } from '@/constants/theme';
import { requireSupabase } from '@/lib/supabase';

const services=[{name:'AI Astrology',icon:Stars,tint:'#EEEBFF'},{name:'Tarot Reading',icon:Sparkles,tint:'#FCECF0'},{name:'Daily Insight',icon:MoonStar,tint:'#FFF5E5'},{name:'Birth Chart',icon:Compass,tint:'#E7F2F4'},{name:'Astrology Reports',icon:BookOpen,tint:'#E8EDFC'},{name:'Courses',icon:CalendarDays,tint:'#F4EAF7'}];
export default function HomeScreen(){const [name,setName]=useState('');useEffect(()=>{void requireSupabase().auth.getUser().then(async({data})=>{if(!data.user)return;const {data:profile}=await requireSupabase().from('profiles').select('display_name').eq('id',data.user.id).maybeSingle();if(profile?.display_name)setName(profile.display_name.split(' ')[0])})},[]);return <Screen dark style={{paddingHorizontal:0,paddingTop:0,paddingBottom:0}}>
 <ScrollView contentContainerStyle={{paddingBottom:12}}>
  <LinearGradient colors={['#17175B','#252B5C','#353A75']} style={{paddingHorizontal:21,paddingTop:14,paddingBottom:23,borderBottomLeftRadius:21,borderBottomRightRadius:21}}>
   <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:23}}><View style={{flexDirection:'row',alignItems:'center',gap:9}}><View style={{width:32,height:32,borderRadius:16,backgroundColor:'#E4DDF0',alignItems:'center',justifyContent:'center'}}><CircleUserRound color={Colors.indigo} size={22}/></View><View><Text style={{fontFamily:'Poppins_600SemiBold',fontSize:14,color:'white'}}>Hello, {name||'Star Seeker'}</Text><Text style={{fontFamily:'Poppins_400Regular',fontSize:9,color:'#E4DDF0'}}>Good morning</Text></View></View><Pressable style={{width:34,height:34,borderRadius:18,backgroundColor:'#FFFFFF20',alignItems:'center',justifyContent:'center'}}><Bell color="white" size={17}/></Pressable></View>
   <View style={{borderRadius:15,overflow:'hidden',padding:16,backgroundColor:'#7770B5'}}><LinearGradient colors={['#A89BE0','#F0CBE0','#FFF0D0']} style={{position:'absolute',left:0,right:0,top:0,bottom:0,opacity:.95}}/><Text style={{fontFamily:'Poppins_600SemiBold',fontSize:18,color:'#29245B',lineHeight:25}}>Discover Answers{ '\n'}for a Brighter Tomorrow</Text><View style={{marginTop:13,height:40,backgroundColor:'white',borderRadius:9,flexDirection:'row',alignItems:'center',paddingHorizontal:11,gap:8}}><SearchIcon/><Text style={{flex:1,color:'#85869A',fontFamily:'Poppins_400Regular',fontSize:10}}>Ask your question</Text><View style={{width:24,height:24,borderRadius:12,backgroundColor:Colors.indigo,alignItems:'center',justifyContent:'center'}}><ChevronRight color="white" size={15}/></View></View></View>
  </LinearGradient>
  <View style={{paddingHorizontal:18,paddingTop:14}}><View style={{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:10}}>{services.map(({name:label,icon:Icon,tint})=><Pressable key={label} onPress={()=>{}} style={{width:'31.7%',height:78,backgroundColor:'#FFFFFF',borderRadius:11,alignItems:'center',justifyContent:'center',gap:6,borderWidth:1,borderColor:'#EFEDF2'}}><View style={{width:34,height:34,borderRadius:10,backgroundColor:tint,alignItems:'center',justifyContent:'center'}}><Icon size={19} color={Colors.indigo}/></View><Text numberOfLines={1} style={{fontFamily:'Poppins_500Medium',fontSize:9,color:Colors.text}}>{label}</Text></Pressable>)}</View>
   <View style={{height:48,backgroundColor:Colors.indigo,borderRadius:11,marginTop:13,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8}}><Wallet color={Colors.gold} size={18}/><View style={{flex:1}}><Text style={{fontFamily:'Poppins_600SemiBold',fontSize:10,color:'white'}}>Your Stars & Credits</Text><Text style={{fontFamily:'Poppins_400Regular',fontSize:8,color:'#D5D2E9'}}>Credits and offers will appear here</Text></View><ChevronRight color="white" size={15}/></View>
   <View style={{height:43,borderRadius:10,marginTop:10,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#39356F'}}><Sparkles color="#F3D994" size={16}/><Text style={{flex:1,fontFamily:'Poppins_500Medium',fontSize:9,color:'white'}}>Daily cosmic guidance</Text><Text style={{fontFamily:'Poppins_400Regular',fontSize:8,color:'#E9DFAF'}}>Coming soon</Text></View>
  </View>
 </ScrollView>
 <View style={{height:58,backgroundColor:'#11154D',borderTopWidth:1,borderColor:'#383968',flexDirection:'row',alignItems:'center',justifyContent:'space-around'}}>{[[Home,'Home'],[Stars,'AI'],[BookOpen,'Reports'],[Wallet,'Credits'],[CircleUserRound,'Profile']].map(([Icon,label]:any)=><Pressable key={label} onPress={()=>label==='Profile'?router.push('/profile'):undefined} style={{alignItems:'center',gap:3}}><Icon size={17} color={label==='Home'?Colors.gold:'#A9A8BC'}/><Text style={{fontFamily:'Poppins_400Regular',fontSize:8,color:label==='Home'?Colors.gold:'#A9A8BC'}}>{label}</Text></Pressable>)}</View>
 </Screen>}
function SearchIcon(){return <Text style={{fontSize:15,color:'#8D8EA0'}}>⌕</Text>}
