import { useMemo, useState } from 'react';
import { router } from 'expo-router';
import { ChevronDown, Search, X } from 'lucide-react-native';
import { countries } from 'countries-list';
import * as Localization from 'expo-localization';
import { FlatList, Modal, Pressable, Text, TextInput, View } from 'react-native';
import { MapArtwork, PrimaryButton, Screen, Title } from '@/components/brand';
import { Colors } from '@/constants/theme';
import { preferences, type RegionChoice } from '@/lib/preferences';

const options=Object.entries(countries).filter(([code,c])=>code.length===2&&!c.userAssigned&&c.currency.length>0).map(([code,c])=>({code,name:c.name,currency:c.currency[0],timezone:Localization.getCalendars()[0]?.timeZone??'UTC',dateFormat:code==='US'?'MM/DD/YYYY':['JP','CN','KR','HU','LT','MN','SE'].includes(code)?'YYYY-MM-DD':'DD/MM/YYYY',flag:String.fromCodePoint(...code.toUpperCase().split('').map(l=>127397+l.codePointAt(0)!))})).sort((a,b)=>a.name.localeCompare(b.name));
export default function RegionScreen(){const detected=Localization.getLocales()[0]?.regionCode;const [choice,setChoice]=useState(options.find(r=>r.code===detected)??options.find(r=>r.code==='IN')!);const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return q?options.filter(r=>r.name.toLocaleLowerCase().includes(q)||r.code.toLocaleLowerCase()===q):options},[query]);const next=async()=>{await preferences.setRegion(choice as RegionChoice);router.push('/language')};
 return <Screen style={{paddingTop:30}}><View style={{flex:1}}><Title subtitle="This helps us show the right language, currency and content for your region.">Where are you located?</Title>
  <Pressable accessibilityRole="button" onPress={()=>setOpen(true)} style={{height:52,backgroundColor:'white',borderWidth:1,borderColor:'#E5E3DF',borderRadius:9,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:10}}><Text style={{fontSize:18}}>{choice.flag}</Text><Text style={{flex:1,color:Colors.text,fontFamily:'Poppins_500Medium',fontSize:12}}>{choice.name}</Text><ChevronDown color={Colors.muted} size={17}/></Pressable>
  <MapArtwork/><Text style={{textAlign:'center',fontFamily:'Poppins_400Regular',fontSize:10,color:Colors.muted,marginTop:4}}>You can update your region any time.</Text><View style={{flex:1}}/><PrimaryButton title="Continue" onPress={next}/><Pressable onPress={()=>router.push('/language')} style={{alignItems:'center',padding:14}}><Text style={{color:Colors.muted,fontFamily:'Poppins_400Regular',fontSize:11}}>Skip for now</Text></Pressable>
 </View>
 <Modal visible={open} animationType="slide" transparent onRequestClose={()=>setOpen(false)}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#0005'}}><View style={{height:'78%',backgroundColor:Colors.ivory,borderTopLeftRadius:22,borderTopRightRadius:22,paddingTop:18,paddingHorizontal:20}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:16}}><Text style={{fontFamily:'Poppins_600SemiBold',fontSize:18,color:Colors.indigo}}>Select your region</Text><Pressable onPress={()=>setOpen(false)}><X color={Colors.indigo} size={22}/></Pressable></View><View style={{height:44,borderWidth:1,borderColor:'#E5E3DF',borderRadius:9,backgroundColor:'white',paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:8,marginBottom:10}}><Search size={16} color={Colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search countries" placeholderTextColor={Colors.muted} style={{flex:1,fontFamily:'Poppins_400Regular',fontSize:12,color:Colors.text}} autoCorrect={false}/></View><FlatList data={filtered} keyExtractor={item=>item.code} keyboardShouldPersistTaps="handled" renderItem={({item})=><Pressable onPress={()=>{setChoice(item);setOpen(false);setQuery('')}} style={{height:48,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:.5,borderBottomColor:'#E9E6E1'}}><Text style={{width:25,fontSize:18}}>{item.flag}</Text><Text numberOfLines={1} style={{fontFamily:'Poppins_400Regular',fontSize:12,color:Colors.text,flex:1}}>{item.name}</Text><Text style={{fontFamily:'Poppins_400Regular',fontSize:10,color:Colors.muted}}>{item.currency}</Text></Pressable>}/></View></View></Modal>
 </Screen>
}
